local CaseRegistry = {}

-- Canonical source cases remain stable for collection migration, archive links and Season 1 lore.
-- Runtime routine jobs are generated by Get(1..5) so the HUD no longer exposes the answer
-- through a memorisable static case title/number.
CaseRegistry.Cases = {
    {
        id = "LF-M0-001", title = "Routine Claim", caseType = "normal", itemId = "hardcase_suitcase", collectionId = "blue_transit_hardcase", bonusCollectionId = "maya_power_adapter", itemName = "Blue Hardcase Suitcase", itemColor = Color3.fromRGB(41, 72, 112), owner = "Maya Chen", claimantName = "Maya Chen", claimantKind = "Adult", tagNumber = "AC-18420", claimantTag = "AC-18420", flight = "GA-417", weight = "11.8 kg", contents = "Clothing, charger, paperback", scanStatus = "RECORD FOUND", anomaly = "None", correctDecision = "RETURN", questionableDecisions = {}, resolution = "CLOSED", risk = "low", reason = "Owner identity and baggage tag match the record.",
    },
    {
        id = "LF-M0-002", title = "Wrong Color", caseType = "normal", itemId = "backpack", collectionId = "crimson_travel_backpack", bonusCollectionId = "daniel_formal_shoe", itemName = "Red Travel Backpack", itemColor = Color3.fromRGB(122, 44, 48), owner = "Daniel Ortiz", claimantName = "Daniel Ortiz", claimantKind = "Adult", tagNumber = "TR-90218", claimantTag = "TR-90218", flight = "QZ-751", weight = "8.2 kg", contents = "Formal clothing, shoes", scanStatus = "CLAIM DESCRIPTION CONFLICT", anomaly = "Claimant repeatedly describes a black backpack; this item is red.", correctDecision = "SECURITY", questionableDecisions = { "STORE" }, resolution = "CLOSED", risk = "medium", reason = "Identity matches, but the claimant's item description conflicts with the physical property. Escalate the suspicious claim.",
    },
    {
        id = "LF-M0-003", title = "Tag Mismatch", caseType = "normal", itemId = "teddy_bear", collectionId = "cream_memory_bear", bonusCollectionId = "sofia_name_patch", itemName = "Cream Teddy Bear", itemColor = Color3.fromRGB(182, 151, 113), owner = "Sofia Rahman", claimantName = "Sofia Rahman", claimantKind = "Adult", tagNumber = "GA-33107", claimantTag = "GA-33170", flight = "GA-883", weight = "1.1 kg", contents = "Stuffed toy with stitched owner label", scanStatus = "TAG NUMBER MISMATCH", anomaly = "None", correctDecision = "STORE", questionableDecisions = { "SECURITY" }, resolution = "CLOSED", risk = "low", reason = "The claimant cannot prove this specific item is theirs. Keep it in storage pending valid documentation.",
    },
    {
        id = "LF-M0-004", title = "No Claimant", caseType = "normal", itemId = "vintage_suitcase", collectionId = "brown_heritage_case", bonusCollectionId = "ari_red_paperback", itemName = "Brown Vintage Suitcase", itemColor = Color3.fromRGB(100, 68, 45), owner = "Ari Pratama", claimantName = nil, claimantKind = "None", tagNumber = "JT-66104", claimantTag = "—", flight = "ID-622", weight = "7.4 kg", contents = "Books, jacket, toiletries", scanStatus = "OWNER RECORD VALID / NO ACTIVE CLAIM", anomaly = "None", correctDecision = "STORE", questionableDecisions = {}, resolution = "CLOSED", risk = "low", reason = "The property is normal but currently unclaimed. Store it.",
    },
    {
        id = "LF-M0-005", title = "False Claim", caseType = "normal", itemId = "hardcase_suitcase", collectionId = "black_security_hardcase", bonusCollectionId = "silver_camera_lens", itemName = "Black Hardcase Suitcase", itemColor = Color3.fromRGB(35, 38, 43), owner = "Emma Laurent", claimantName = "Kevin Brooks", claimantKind = "Adult", tagNumber = "AF-51033", claimantTag = "AF-51033", flight = "AF-129", weight = "12.1 kg", contents = "Clothing, camera lens", scanStatus = "CLAIMANT IDENTITY DOES NOT MATCH OWNER", anomaly = "Claimant has the correct tag number but is not the registered owner.", correctDecision = "SECURITY", questionableDecisions = { "STORE" }, resolution = "CLOSED", risk = "medium", reason = "A non-owner possesses the correct tag number. Escalate potential theft/fraud.",
    },
    {
        id = "LF-M0-006", title = "Ownerless Suitcase", caseType = "mystery", itemId = "vintage_suitcase", collectionId = "ownerless_vintage_case", bonusCollectionId = "ownerless_tag_00017284", itemName = "Ownerless Vintage Suitcase", itemColor = Color3.fromRGB(70, 45, 36), owner = "UNKNOWN", claimantName = nil, claimantKind = "None", tagNumber = "000-17284", claimantTag = "—", flight = "000", weight = "18.0 kg", contents = "No declared contents", scanStatus = "NO OWNER / NO VALID FLIGHT RECORD", anomaly = "The tag exists physically but has no database origin.", correctDecision = "QUARANTINE", questionableDecisions = { "STORE" }, resolution = "CONNECTED", risk = "high", reason = "An item with no valid owner and impossible origin must be contained, not returned or stored with normal property.",
    },
    {
        id = "LF-M0-007", title = "Flight 000", caseType = "mystery", itemId = "hardcase_suitcase", collectionId = "flight_000_hardcase", bonusCollectionId = "flight_000_boarding_tag", itemName = "Flight 000 Suitcase", itemColor = Color3.fromRGB(24, 28, 36), owner = "Jonas Vale", claimantName = "Jonas Vale", claimantKind = "Adult", tagNumber = "F0-00013", claimantTag = "F0-00013", flight = "000", weight = "13.0 kg", contents = "Unclear image on X-ray placeholder", scanStatus = "PASSENGER FOUND / FLIGHT NOT FOUND", anomaly = "The passenger record exists, but Flight 000 does not exist in the terminal schedule.", correctDecision = "QUARANTINE", questionableDecisions = { "SECURITY" }, resolution = "CONNECTED", risk = "high", reason = "The item's transport origin is impossible. Contain the item for anomaly review.",
    },
    {
        id = "LF-M0-008", title = "Changing Weight", caseType = "mystery", itemId = "cardboard_box", collectionId = "unstable_sealed_parcel", bonusCollectionId = "unstable_mass_readout", itemName = "Sealed Cardboard Parcel", itemColor = Color3.fromRGB(147, 108, 70), owner = "Nina Ward", claimantName = "Nina Ward", claimantKind = "Adult", tagNumber = "SQ-22191", claimantTag = "SQ-22191", flight = "SQ-944", weight = "7.0 kg → 43.0 kg", contents = "Appears empty", scanStatus = "MASS READING UNSTABLE", anomaly = "Repeated scans return incompatible weight values while the sealed parcel appears empty.", correctDecision = "QUARANTINE", questionableDecisions = { "SECURITY" }, resolution = "RESOLVED", risk = "high", reason = "Impossible physical readings require quarantine even when identity appears valid.",
    },
    {
        id = "LF-M0-009", title = "Double Identity", caseType = "mystery", itemId = "backpack", collectionId = "green_identity_backpack", bonusCollectionId = "duplicate_passport", itemName = "Green Travel Backpack", itemColor = Color3.fromRGB(55, 82, 66), owner = "Elias North", claimantName = "Elias North", claimantKind = "Adult", tagNumber = "KL-44381", claimantTag = "KL-44381", flight = "KL-836", weight = "6.2 kg", contents = "Two passports with the same name and different birth dates", scanStatus = "IDENTITY CONFLICT", anomaly = "Two valid-looking identities exist for one claimant.", correctDecision = "SECURITY", questionableDecisions = { "QUARANTINE" }, resolution = "UNRESOLVED", risk = "high", reason = "The immediate threat is an identity incident involving a person. Security must take control of the claimant and evidence.",
    },
    {
        id = "LF-M0-010", title = "The Lost Child", caseType = "mystery", itemId = "vintage_suitcase", collectionId = "milo_small_case", bonusCollectionId = "milo_toy_train_2001", itemName = "Small Vintage Case", itemColor = Color3.fromRGB(86, 58, 43), owner = "Milo Hart", claimantName = "Milo Hart", claimantKind = "Child", tagNumber = "OLD-2001-14", claimantTag = "OLD-2001-14", flight = "ARCHIVED / 2001", weight = "3.1 kg", contents = "Toy train, old family photograph", scanStatus = "MISSING PERSON RECORD / 2001", anomaly = "The child matches a missing-person photo archived twenty-five years earlier.", correctDecision = "SECURITY", questionableDecisions = { "QUARANTINE" }, resolution = "CONNECTED", risk = "high", reason = "Protect and escalate the child. Do not treat a person as property and do not attempt to solve the anomaly alone.",
    },
}

local RNG = Random.new()
local runtimeCounter = 0
local MYSTERY_CANDIDATE_CHANCE = 0.35

local NAMES = {
    "Alya Putri", "Rafi Santoso", "Dimas Kurnia", "Nadia Prameswari", "Kevin Lim",
    "Mei Tan", "Hana Suzuki", "Kenji Mori", "Min Jae Park", "Soo Jin Lee",
    "Amira Hassan", "Omar Khalid", "Leila Farah", "Yusuf Rahman", "Maya Chen",
    "Daniel Ortiz", "Sofia Rahman", "Ari Pratama", "Emma Laurent", "Noah Bennett",
    "Lena Fischer", "Mateo Silva", "Camila Torres", "Lucas Martin", "Chloe Dubois",
    "Samir Patel", "Priya Nair", "Arjun Mehta", "Anika Rao", "Ethan Brooks",
    "Olivia Ward", "Mila Novak", "Leo Anders", "Sara Costa", "Adam Wilson",
    "Inez Romero", "Theo Grant", "Nora Ibrahim", "Farah Malik", "Kai Morgan",
    "Rina Sato", "Jae Kim", "Tariq Aziz", "Elena Rossi", "Marco Bellini",
    "Grace Lee", "Nathan Cole", "Zara Ahmed", "Julian Cross", "Mina Park",
}

local AIRLINES = { "GA", "QZ", "SQ", "KL", "AF", "TR", "ID", "JT", "CX", "TG", "MH", "BR" }
local ALT_COLORS = { "black", "blue", "red", "green", "cream", "brown", "silver", "navy" }

local ITEM_PROFILES = {
    {
        sourceId = "LF-M0-001", itemId = "hardcase_suitcase", collectionId = "blue_transit_hardcase", bonusCollectionId = "maya_power_adapter",
        itemName = "Blue Hardcase Suitcase", colorName = "blue", itemColor = Color3.fromRGB(41, 72, 112),
        contents = { "Clothing, charger, paperback", "Two shirts, travel adapter, notebook", "Jacket, toiletries, phone cable" },
        minWeight = 85, maxWeight = 148,
    },
    {
        sourceId = "LF-M0-002", itemId = "backpack", collectionId = "crimson_travel_backpack", bonusCollectionId = "daniel_formal_shoe",
        itemName = "Red Travel Backpack", colorName = "red", itemColor = Color3.fromRGB(122, 44, 48),
        contents = { "Formal clothing, shoes", "Tablet sleeve, shirt, headphones", "Documents, sweater, shoes" },
        minWeight = 42, maxWeight = 96,
    },
    {
        sourceId = "LF-M0-003", itemId = "teddy_bear", collectionId = "cream_memory_bear", bonusCollectionId = "sofia_name_patch",
        itemName = "Cream Teddy Bear", colorName = "cream", itemColor = Color3.fromRGB(182, 151, 113),
        contents = { "Stuffed toy with stitched owner label", "Stuffed toy with fabric name patch", "Stuffed toy with small ribbon and stitched initials" },
        minWeight = 7, maxWeight = 18,
    },
    {
        sourceId = "LF-M0-004", itemId = "vintage_suitcase", collectionId = "brown_heritage_case", bonusCollectionId = "ari_red_paperback",
        itemName = "Brown Vintage Suitcase", colorName = "brown", itemColor = Color3.fromRGB(100, 68, 45),
        contents = { "Books, jacket, toiletries", "Paperback novels, scarf, shaving kit", "Clothes, old notebook, toiletries" },
        minWeight = 58, maxWeight = 122,
    },
    {
        sourceId = "LF-M0-005", itemId = "hardcase_suitcase", collectionId = "black_security_hardcase", bonusCollectionId = "silver_camera_lens",
        itemName = "Black Hardcase Suitcase", colorName = "black", itemColor = Color3.fromRGB(35, 38, 43),
        contents = { "Clothing, camera lens", "Camera pouch, jacket, cables", "Clothing, lens case, memory-card wallet" },
        minWeight = 92, maxWeight = 151,
    },
}

local function pick(list)
    return list[RNG:NextInteger(1, #list)]
end

local function randomName(exclude)
    local value = pick(NAMES)
    local guard = 0
    while value == exclude and guard < 8 do
        value = pick(NAMES)
        guard += 1
    end
    return value
end

local function randomFlight()
    return pick(AIRLINES) .. "-" .. tostring(RNG:NextInteger(101, 989))
end

local function randomTag()
    return pick(AIRLINES) .. "-" .. string.format("%05d", RNG:NextInteger(1000, 99999))
end

local function changedTag(tag)
    local prefix, digits = string.match(tag, "^(%a+%-)(%d+)$")
    if not prefix or not digits then return tag .. "X" end
    local last = tonumber(string.sub(digits, -1)) or 0
    local replacement = (last + RNG:NextInteger(1, 8)) % 10
    return prefix .. string.sub(digits, 1, #digits - 1) .. tostring(replacement)
end

local function randomWeight(profile)
    local tenths = RNG:NextInteger(profile.minWeight, profile.maxWeight)
    return string.format("%.1f kg", tenths / 10)
end

local function alternateColor(actual)
    local result = pick(ALT_COLORS)
    local guard = 0
    while result == actual and guard < 8 do
        result = pick(ALT_COLORS)
        guard += 1
    end
    return result
end

local function baseRoutine(profile)
    runtimeCounter += 1
    local owner = randomName(nil)
    local tag = randomTag()
    return {
        id = string.format("LF-R-%06d-%02d", RNG:NextInteger(0, 999999), runtimeCounter % 100),
        sourceCaseId = profile.sourceId,
        title = "Property Review",
        caseType = "normal",
        itemId = profile.itemId,
        collectionId = profile.collectionId,
        bonusCollectionId = profile.bonusCollectionId,
        itemName = profile.itemName,
        itemColor = profile.itemColor,
        owner = owner,
        claimantName = owner,
        claimantKind = "Adult",
        tagNumber = tag,
        claimantTag = tag,
        flight = randomFlight(),
        weight = randomWeight(profile),
        contents = pick(profile.contents),
        scanStatus = "RECORD FOUND",
        anomaly = "None",
        correctDecision = "RETURN",
        questionableDecisions = {},
        resolution = "CLOSED",
        risk = "low",
        reason = "Identity, tag and property record support the same claimant.",
        runtimeRoutine = true,
    }
end

local SCENARIOS = {}

SCENARIOS.verified_return = function(c)
    c.scanStatus = "OWNER / TAG / ROUTING RECORD MATCH"
    c.reason = "Owner identity, claim tag and routing record all match the property."
end

SCENARIOS.delayed_scan_return = function(c)
    c.scanStatus = "OWNER MATCH / ROUTING UPDATE DELAYED"
    c.anomaly = "The transfer scan posted late, but the physical tag and claimant identity both match."
    c.reason = "A delayed routing update alone does not invalidate a verified owner and matching physical tag."
end

SCENARIOS.manual_tag_return = function(c)
    c.scanStatus = "BARCODE DAMAGED / MANUAL SERIAL MATCH"
    c.anomaly = "Barcode is unreadable; the printed serial, owner ID and claim receipt match exactly."
    c.reason = "The damaged barcode is compensated by matching manual serial, owner identity and claim receipt."
end

SCENARIOS.no_claimant_store = function(c)
    c.claimantName = nil
    c.claimantKind = "None"
    c.claimantTag = "—"
    c.scanStatus = "OWNER RECORD VALID / NO ACTIVE CLAIM"
    c.correctDecision = "STORE"
    c.reason = "The item has a valid record but nobody is currently proving a claim. Keep it stored."
end

SCENARIOS.tag_mismatch_store = function(c)
    c.claimantTag = changedTag(c.tagNumber)
    c.scanStatus = "CLAIM TAG DOES NOT MATCH PROPERTY"
    c.correctDecision = "STORE"
    c.questionableDecisions = { "SECURITY" }
    c.reason = "The claimant identity may be genuine, but the supplied claim tag does not prove ownership of this item."
end

SCENARIOS.no_tag_store = function(c)
    c.claimantTag = "NOT PROVIDED"
    c.scanStatus = "OWNER NAME FOUND / CLAIM PROOF INCOMPLETE"
    c.anomaly = "Claimant knows the owner name but cannot provide the claim tag or receipt."
    c.correctDecision = "STORE"
    c.reason = "Knowledge of the owner name is not enough to release property without proof tied to this item."
end

SCENARIOS.finder_store = function(c)
    c.claimantName = randomName(c.owner)
    c.claimantKind = "Finder"
    c.claimantTag = "FINDER TURN-IN"
    c.scanStatus = "THIRD-PARTY FINDER / OWNER RECORD FOUND"
    c.anomaly = "The person at the desk says they found the item and is not claiming ownership."
    c.correctDecision = "STORE"
    c.questionableDecisions = {}
    c.reason = "A finder is surrendering the property, not claiming it. Store it for the registered owner."
end

SCENARIOS.description_conflict_security = function(c, profile)
    local claimed = alternateColor(profile.colorName)
    c.scanStatus = "CLAIM DESCRIPTION CONFLICT"
    c.anomaly = "Claimant repeatedly describes a " .. claimed .. " item; the inspected property is " .. profile.colorName .. "."
    c.correctDecision = "SECURITY"
    c.questionableDecisions = { "STORE" }
    c.risk = "medium"
    c.reason = "The claimant has matching paperwork but gives a materially wrong physical description. Escalate possible fraud."
end

SCENARIOS.identity_mismatch_security = function(c)
    c.claimantName = randomName(c.owner)
    c.scanStatus = "CLAIMANT IDENTITY DOES NOT MATCH REGISTERED OWNER"
    c.anomaly = "The claimant presents the exact tag number but their identity differs from the registered owner."
    c.correctDecision = "SECURITY"
    c.questionableDecisions = { "STORE" }
    c.risk = "medium"
    c.reason = "A non-owner possessing the exact claim tag requires a security review for possible theft or fraud."
end

SCENARIOS.duplicate_claim_security = function(c)
    c.scanStatus = "DUPLICATE ACTIVE CLAIM DETECTED"
    c.anomaly = "A second person submitted a verified-looking claim for this exact tag less than ten minutes earlier."
    c.correctDecision = "SECURITY"
    c.questionableDecisions = { "STORE" }
    c.risk = "medium"
    c.reason = "Two competing verified-looking claims for one tag require security to preserve evidence and identities."
end

SCENARIOS.tampered_tag_security = function(c)
    c.scanStatus = "TAG ALTERATION DETECTED"
    c.anomaly = "Scanner detects two adhesive layers and overwritten digits beneath the visible claim tag."
    c.correctDecision = "SECURITY"
    c.questionableDecisions = { "STORE" }
    c.risk = "high"
    c.reason = "Physical evidence of claim-tag tampering indicates possible deliberate fraud."
end

SCENARIOS.copied_tag_security = function(c)
    c.scanStatus = "TAG SERIAL DUPLICATED ON ANOTHER ACTIVE ITEM"
    c.anomaly = "The same tag number is currently registered to a different item in another terminal record."
    c.correctDecision = "SECURITY"
    c.questionableDecisions = { "STORE" }
    c.risk = "high"
    c.reason = "A duplicated live tag is evidence of possible label cloning or fraud and must be escalated."
end

SCENARIOS.contents_conflict_store = function(c)
    c.scanStatus = "IDENTITY MATCH / CONTENT DESCRIPTION CONFLICT"
    c.anomaly = "Claimant identity and tag match, but their listed contents do not match the inspected contents."
    c.correctDecision = "STORE"
    c.questionableDecisions = { "SECURITY" }
    c.risk = "low"
    c.reason = "Conflicting contents weaken proof of this specific property. Hold it in storage pending better documentation."
end

SCENARIOS.unsafe_battery_quarantine = function(c)
    c.scanStatus = "THERMAL WARNING / INTERNAL BATTERY SWELLING"
    c.anomaly = "Inspection finds a hot, swollen battery pack inside the property."
    c.correctDecision = "QUARANTINE"
    c.questionableDecisions = { "SECURITY" }
    c.risk = "high"
    c.reason = "The immediate issue is a hazardous item requiring controlled isolation, regardless of ownership."
end

SCENARIOS.liquid_leak_quarantine = function(c)
    c.scanStatus = "UNKNOWN LIQUID LEAK DETECTED"
    c.anomaly = "A sealed inner container is leaking an unidentified liquid with no declaration in the property record."
    c.correctDecision = "QUARANTINE"
    c.questionableDecisions = { "SECURITY" }
    c.risk = "high"
    c.reason = "Unknown leaking material must be isolated before normal storage, return or investigative handling."
end

local EASY = { "verified_return", "no_claimant_store", "tag_mismatch_store", "identity_mismatch_security", "delayed_scan_return" }
local MEDIUM = { "verified_return", "no_claimant_store", "tag_mismatch_store", "identity_mismatch_security", "delayed_scan_return", "manual_tag_return", "no_tag_store", "finder_store", "description_conflict_security", "contents_conflict_store" }
local FULL = { "verified_return", "delayed_scan_return", "manual_tag_return", "no_claimant_store", "tag_mismatch_store", "no_tag_store", "finder_store", "description_conflict_security", "identity_mismatch_security", "duplicate_claim_security", "tampered_tag_security", "copied_tag_security", "contents_conflict_store", "unsafe_battery_quarantine", "liquid_leak_quarantine" }

local function generateRoutine(profileIndex, tier)
    local profile = ITEM_PROFILES[profileIndex] or pick(ITEM_PROFILES)
    local c = baseRoutine(profile)
    local pool = tier == "easy" and EASY or (tier == "medium" and MEDIUM or FULL)
    local scenarioId = pick(pool)
    c.scenarioId = scenarioId
    SCENARIOS[scenarioId](c, profile)
    return c
end

function CaseRegistry.Get(index)
    if index >= 1 and index <= 5 then
        local tier = index <= 2 and "easy" or (index == 3 and "medium" or "full")
        return generateRoutine(index, tier)
    end

    if index >= 6 and index <= 10 then
        -- Mystery cases remain progression-gated by PersonalShiftRuntime but are not
        -- guaranteed candidates every cycle. This keeps canon incidents special and
        -- prevents experienced players from seeing Flight 000 every few jobs.
        if RNG:NextNumber() <= MYSTERY_CANDIDATE_CHANCE then
            return CaseRegistry.Cases[index]
        end
        return generateRoutine(RNG:NextInteger(1, #ITEM_PROFILES), "full")
    end

    return CaseRegistry.Cases[index]
end

function CaseRegistry.GetCanonical(index)
    return CaseRegistry.Cases[index]
end

function CaseRegistry.Count()
    return #CaseRegistry.Cases
end

return CaseRegistry
