-- M4-C compatibility marker.
-- Economy/playtime/mint/case telemetry is now owned by PersonalShiftRuntime so
-- personal stations cannot double-count another player's prompt interactions.
-- TradeService continues to own trade request/completion/cancellation telemetry.
